# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\Sniwt-home\Desktop\работа с excel и БД в pyton\EditeBDFrm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DBEditeForm(object):
    def setupUi(self, DBEditeForm):
        DBEditeForm.setObjectName("DBEditeForm")
        DBEditeForm.resize(508, 201)
        self.AddRecBt = QtWidgets.QPushButton(DBEditeForm)
        self.AddRecBt.setGeometry(QtCore.QRect(20, 80, 181, 23))
        self.AddRecBt.setObjectName("AddRecBt")
        self.FindeRecBt = QtWidgets.QPushButton(DBEditeForm)
        self.FindeRecBt.setGeometry(QtCore.QRect(20, 120, 181, 23))
        self.FindeRecBt.setObjectName("FindeRecBt")
        self.RemRecBt = QtWidgets.QPushButton(DBEditeForm)
        self.RemRecBt.setGeometry(QtCore.QRect(20, 160, 181, 23))
        self.RemRecBt.setObjectName("RemRecBt")
        self.SQLBt = QtWidgets.QPushButton(DBEditeForm)
        self.SQLBt.setGeometry(QtCore.QRect(290, 60, 181, 23))
        self.SQLBt.setObjectName("SQLBt")
        self.SQLKonstrBt = QtWidgets.QPushButton(DBEditeForm)
        self.SQLKonstrBt.setGeometry(QtCore.QRect(290, 90, 181, 23))
        self.SQLKonstrBt.setObjectName("SQLKonstrBt")
        self.TabNameCB = QtWidgets.QComboBox(DBEditeForm)
        self.TabNameCB.setGeometry(QtCore.QRect(20, 40, 201, 22))
        self.TabNameCB.setObjectName("TabNameCB")
        self.label = QtWidgets.QLabel(DBEditeForm)
        self.label.setGeometry(QtCore.QRect(20, 20, 211, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DBEditeForm)
        self.label_2.setGeometry(QtCore.QRect(290, 40, 181, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(DBEditeForm)
        QtCore.QMetaObject.connectSlotsByName(DBEditeForm)

    def retranslateUi(self, DBEditeForm):
        _translate = QtCore.QCoreApplication.translate
        DBEditeForm.setWindowTitle(_translate("DBEditeForm", "Работа с базой данных"))
        self.AddRecBt.setText(_translate("DBEditeForm", "Добавить запись в таблицу"))
        self.FindeRecBt.setText(_translate("DBEditeForm", "Найти запись в таблице"))
        self.RemRecBt.setText(_translate("DBEditeForm", "Удалить запись в таблице"))
        self.SQLBt.setText(_translate("DBEditeForm", "Сформировать SQL запрос"))
        self.SQLKonstrBt.setText(_translate("DBEditeForm", "Конструктор запросов"))
        self.label.setText(_translate("DBEditeForm", "Выберете таблицу для редактирования"))
        self.label_2.setText(_translate("DBEditeForm", "Общие действия над БД"))
